on: [workflow_dispatch]
name: Update Saved Pools
jobs:
  update_saved_pools:
    name: Update Saved Pools
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true
          
      - name: Git Sumbodule Update
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19.6.0
          
      - name: Run code to Query Pools
        working-directory: ./.github/workflows/utility
        run: node queryPools.mjs

      - name: Add Commit Push
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          add_timestamp: false
          commit_prefix: "[AUTO]"
          commit_message: "Query and Save Pools"
          force: false
          target_branch: update/query_pools
      
      - name: Create A PR
        uses: devops-infra/action-pull-request@v0.4.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: update/query_pools
          target_branch: main
          title: Query and Save Pools
          body: "**Automated pull request**"
          old_string: "**THIS IS AN AUTOMATED UPDATE OF ALL POOLS**"
          new_string: "** Automatic pull request**"
          get_diff: true
          ignore_users: "dependabot"
